theme = "tabi"
title = "Parth"
# 
# The URL the site will be built for
base_url = "https://parth.github.io/parth.cafe"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[taxonomies]
tags = ["lockbook", "programming", "personal development", "wrenching", "miata"]

[markdown]
highlight_code = true

[extra]
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

socials = [
    { name = "github", url = "https://github.com/parth/", icon = "github" },
    { name = "instagram", url = "https://instagram.com/mehrotraparth", icon = "instagram" },
    { name = "youtube", url = "https://www.youtube.com/@ParthMehrotra", icon = "youtube" },
    { name = "spotify", url = "https://open.spotify.com/user/1246406255?si=74cbe323cc604663", icon = "spotify" },
]
